[[bin]]
name = "parse-frame"
path = "parse_frame.rs"

[[bin]]
name = "unmask"
path = "unmask.rs"

[dependencies]
libfuzzer-sys = { default-features = false, version = "0.4" }
tokio = { default-features = false, features = ["rt"], version = "1.0" }
wtx = { default-features = false, path = "../wtx" }

[package]
name = "wtx-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true
