name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2021-12-19

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          use-tool-cache: true

      - run: .scripts/fuzz.sh

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          profile: minimal
          toolchain: 1.61.0

      - uses: Swatinem/rust-cache@v1

      - run: .scripts/all.sh
